### PR TITLE
Fix virtual trap at the end of the program

### LINKED ISSUE #139: Step allows to reset the state
Step allows to reset the state
https://github.com/user-attachments/assets/d593c4fc-663f-4643-ad90-26463d106fd9

### PR DESCRIPTION
**Pull request by wkwiatek**
Fixes #139

### CODE REVIEW

**Comment by tomusdrw** [comment]
image
The branch code halts on the branch itself, which doesn't seem to be correct. Not sure if this is caused by this PR or something else. @mateuszsikora maybe take a look too.

**Comment by tomusdrw** [comment]
Okay, it only happens after I loaded fib example first, so might be fixed by https://github.com/FluffyLabs/typeberry/pull/161 (i.e. issue with jump table).

**Comment by wkwiatek** [comment]
@tomusdrw I believe this is exactly the case. Also reported here: https://github.com/FluffyLabs/pvm-debugger/issues/140

**Comment by krystian50** [comment]
@wkwiatek does it fix the #140? Could you close the issue if so.

**Pull request merged**
